Auto login using Openlogin session
torusresearch/torus-website pull request #1988
Opened 2022-06-14 05:39 UTC by tainguyentt

2022-08-05 07:58 UTC, tainguyentt reviewed
tested in Chrome, Firefox, Safari, Brave, and it worked for me.

2022-08-05 07:58 UTC, tainguyentt commented on src/handlers/Auth/OpenLoginHandler.js
> +      log.info(this.openLoginInstance.state.store.getStore(), 'store')
remove log

2022-08-05 07:58 UTC, tainguyentt commented on src/handlers/Auth/OpenLoginHandler.js
> +    log.info(this.openLoginInstance.state.store.getStore())
remove log

2022-08-05 08:27 UTC, chaitanyapotti approved these changes
lgtm

2022-08-05 12:05 UTC, himanshuchawla009 requested changes

2022-08-05 12:28 UTC, himanshuchawla009 commented
https://user-images.githubusercontent.com/14052374/183077149-cc70f020-b336-463a-acaf-e3f677b4bf1f.mov

there is some lag in opening embed widget

2022-08-05 12:32 UTC, himanshuchawla009 commented
logout event is not propagating from wallet to embed.

- login with embed
- Open wallet via embed widget
- logout from wallet
- User still remains logged in dapp

2022-08-08 07:05 UTC, chaitanyapotti commented on src/config.js
> +export function storageAvailable(type) {
we would create a circular dependency otherwise

2022-08-08 08:57 UTC, tainguyentt commented
I did one round of testing across browsers (Chrome, Brave, Safari, Firefox) and didn't find any issue yet

2022-08-08 09:51 UTC, himanshuchawla009 approved these changes
lgtm

2022-08-08 09:52 UTC, merged