add mfa support
torusresearch/torus-website pull request #2048
Opened 2022-08-10 17:55 UTC by rinzler99

Task: https://toruslabs.atlassian.net/browse/PD-1019

Demo:https://www.loom.com/share/d9fc9663f53b40628d852217da3eb812

2022-08-11 07:53 UTC, himanshuchawla009 requested changes

2022-08-11 07:53 UTC, himanshuchawla009 commented on src/store/mutations.js
> +      mfaLevel: payload || 'optional',
not neeed of  || 'optional' here

2022-08-11 07:53 UTC, himanshuchawla009 commented on src/store/setupStoreChannels.js
> +        mfaLevel = 'optional',
keep it null by default

2022-08-11 07:53 UTC, himanshuchawla009 commented on src/store/state.js
> +    mfaLevel: 'optional',
keep it null

2022-08-11 08:06 UTC, rinzler99 commented on src/store/mutations.js
> +      mfaLevel: payload || 'optional',
resolved

2022-08-15 06:16 UTC, chaitanyapotti commented on src/store/state.js
> +    mfaLevel: null,
use 'default' as default value

2022-08-15 06:29 UTC, chaitanyapotti approved these changes
lgtm

2022-08-15 06:29 UTC, merged